---
dependencies: 
  - gcc
  - libc6
  - libc6-dev
  - build-essential

  - libbz2-dev
  - libncurses5-dev
  - libgdbm-dev
  - liblzma-dev
  - sqlite3
  # - libsqlite3-dev
  - openssl
  # - libssl-dev
  # - tcl8.6-dev
  # - tk8.6-dev
  # - libreadline-dev
  - zlib1g-dev
